Add submodule update commit to branch

diff --git a/.github/workflows/collect-branch.yml b/.github/workflows/collect-branch.yml
--- a/.github/workflows/collect-branch.yml
+++ b/.github/workflows/collect-branch.yml
@@ -326,7 +326,15 @@ jobs:
 
       - name: Update Submodules if needed
         shell: bash
-        run: git submodule update --init --recursive --remote
+        run: |
+          git submodule update --init --recursive --remote
+          set +e
+          git commit -am "Update Submodules"
+          if [ $? -eq 1 ];then
+            echo "No push required"
+          else
+            git push
+          fi
 
       - name: Bundle Repo1 code base for ${{ vars.COLLECTOR }}
         run: |
